# Generated by Django 5.2.4 on 2026-01-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('accessory', 'Accessory'), ('shoe', 'Shoe')], max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('colors_json', models.TextField(default='[]', help_text='List of available colors')),
                ('sizes_json', models.TextField(default='[]', help_text='List of available sizes')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommended_products', models.ManyToManyField(blank=True, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(blank=True, choices=[('hourglass', 'Hourglass'), ('pear', 'Pear'), ('apple', 'Apple'), ('rectangle', 'Rectangle'), ('inverted_triangle', 'Inverted Triangle')], max_length=50)),
                ('preferred_styles', models.CharField(blank=True, help_text='Comma-separated styles e.g. casual, formal', max_length=200)),
                ('budget_min', models.IntegerField(default=0)),
                ('budget_max', models.IntegerField(default=10000)),
                ('favorite_colors', models.CharField(blank=True, max_length=200)),
                ('occasions', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
